# *
# * This Source Code Form is subject to the terms of the Mozilla Public
# * License, v. 2.0. If a copy of the MPL was not distributed with this
# * file, You can obtain one at http://mozilla.org/MPL/2.0/.

# *****************************************************************
# This is the DEVELOPER Docker configuration file that is used for
# developers. It should NOT be used for production sites as that
# can introduce security issues. Developers should start OED with:
# docker compose -f docker-compose.yml -f docker-compose-dev.yml up
# or an appropriate variant to cause the values in this file to override
# the ones in the default docker file.
# *****************************************************************

version: "3.8"
services:
    database:
        # The next lines enable access to the PostgreSQL server from the host machine.
        # It can be very valuable for debugging the database via tools such as PGAdmin.
        # They can be commented out to close that port but it will stop that type of debugging.
        ports:
           - "5432:5432"
    web:
        environment:
            # Set this value to yes or no, other values wil result in a configuration error.
            # Unless you are testing a production setup, this is normally no.
            - OED_PRODUCTION=no
            # This is to let the install know that the second, developer docker file was used.
            # It is mostly as a safety check and during the transition to warn developers to
            # transition to the new system. It should NOT be changed.
            # The value is not set in the production config file to avoid someone wanting to
            # set it there and that is not desired.
            - OED_DOCKER_CONFIG_DEV=yes
        ports:
            # If you are experiencing port conflicts with 3000 then you can modify this to
            # use another port. For example, to switch to port xxxx you would do:
            # "xxxx:3000"
            - "3000:3000"
            # This enables debugging as a developer.
            - "9229:9229"
        command:
            [
                "bash",
                "./src/scripts/installOED.sh",
                # This allows for starting OED with special values for a developer.
                # See developer docs for details.
                "${install_args:-}"
            ]

    # Cypress testing service
    # This is used for UI testing and normally only creates this Docker container
    # if you specially start up UI testing.
    cypress:
      image: cypress/included
      profiles:
        - ui-testing
      environment:
        - CYPRESS_BASE_URL=http://web:3000
        - DISPLAY=:99
      working_dir: /usr/src/app
      depends_on:
        web:
          condition: service_healthy
      volumes:
        - ./:/usr/src/app
      entrypoint: >
        /bin/sh -c "
        rm -f /tmp/.X99-lock &&
        Xvfb :99 -screen 0 1024x768x16"
      read_only: true
      security_opt:
        - no-new-privileges:true
