REFRESH MATERIALIZED VIEW CONCURRENTLY minutely_readings ;
REFRESH MATERIALIZED VIEW CONCURRENTLY hourly_readings;
REFRESH MATERIALIZED VIEW CONCURRENTLY daily_readings;
REFRESH MATERIALIZED VIEW CONCURRENTLY monthly_readings;
REFRESH MATERIALIZED VIEW CONCURRENTLY yearly_readings;
