# *
# * This Source Code Form is subject to the terms of the Mozilla Public
# * License, v. 2.0. If a copy of the MPL was not distributed with this
# * file, You can obtain one at http://mozilla.org/MPL/2.0/.
# *

version: '3.8'
services:
  web:
    volumes:
      - .:/workspace:cached

    # Keep the container alive
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Forward Node debug port 9229 inside container to a safe host port 3000
    ports:
      - "3000:9229"

    # Uncomment these if you need ptrace-based debugging for C++, Go, Rust
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
