// Utility functions for determining compatible units for meters and groups

/**
 * Returns the set of unit IDs compatible with a given meter's unit.
 * @param {number} unitId - The unit ID of the meter.
 * @param {Array<{source: number, destination: number}>} cikArray - The CIK array representing conversion paths. (The one generated by createCikArray)
 * @returns {Set<number>} Set of compatible unit IDs.
 */
function compatibleUnitsForMeter(unitId, cikArray) {
	if (unitId == -99) {
		return new Set();
	}
	return new Set(cikArray.filter(cik => cik.source === unitId).map(cik => cik.destination));
}
/**
 * Returns the intersection of multiple sets.
 * @param {Array<Set<number>>} sets - Array of sets to intersect.
 * @returns {Set<number>} Intersection of all sets, or empty set if input is empty.
 */
function intersectSets(sets) {
	if (!sets.length) {
		return new Set();
	}
	return sets.reduce((a, b) => new Set([...a].filter(x => b.has(x))));
}


module.exports = {
	compatibleUnitsForMeter,
	intersectSets,
};