global class CommerceProductSummary {
	global ConnectApi.CommerceProductSellingModel productSellingModelInformation;
	global ConnectApi.PurchaseQuantityRule purchaseQuantityRule;
	global ConnectApi.CommerceProductAttributeSetSummary variationAttributeSet;
	global CommerceProductSummary() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}