global class GenAiActionInput {
	global String description;
	global String id;
	global String input;
	global String invocationTarget;
	global String invocationTargetName;
	global String invocationTargetType;
	global Boolean isConfirmationRequired;
	global String masterLabel;
	global String name;
	global String namespace;
	global String output;
	global GenAiActionInput() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Integer hashCode() { }
	global String toString() { }

}