global class LearningStatus {
	global String academicSeason;
	global String academicTermEnrollmentId;
	global String academicTermId;
	global String academicYear;
	global String durationUnit;
	global String learningId;
	global String letterGrade;
	global Double numericGrade;
	global String resultStatus;
	global String status;
	global Double unitsEarned;
	global LearningStatus() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}