global class MlRetrieverQueryResultDocumentRepresentation {
	global List<ConnectApi.MlRetrieverQueryResultDocumentContentRepresentation> contents;
	global Double keywordSearchScore;
	global Double vectorSearchScore;
	global MlRetrieverQueryResultDocumentRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}