global class ProcedurePlanSectionEvaluationRuntimeRepresentation {
	global String expressionSetApiName;
	global String expressionSetDefinitionId;
	global String expressionSetLabel;
	global String readContextMapping;
	global String saveContextMapping;
	global String sectionType;
	global Integer sequence;
	global String subSectionType;
	global String usageType;
	global ProcedurePlanSectionEvaluationRuntimeRepresentation() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}