global class ProductOverview {
	global ConnectApi.ProductMedia defaultImage;
	global ConnectApi.ErrorResponse error;
	global Map<String,String> fields;
	global String id;
	global ConnectApi.PricingResultLineItem prices;
	global String sku;
	global Boolean success;
	global ProductOverview() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}