global class SearchObject {
	global List<ConnectApi.ResponseField> displayFields;
	global String label;
	global String labelPlural;
	global String objectApiName;
	global List<ConnectApi.SearchResult> searchResults;
	global SearchObject() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}