global class ServicePlanSummary {
	global String copilot;
	global String feedbackId;
	global String generatedPlanId;
	global ConnectApi.ServicePlanGenerationSessionInformationOutput sessionInformation;
	global String topic;
	global String topicDescription;
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}