name: Build Docker

on:
    pull_request:
        branches: [ development ]
    push:
        branches: [ development ]

jobs:
    run-docker-checks-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Create .env file for Docker Compose
              run: |
                  cat <<EOF > .env
                  OED_SERVER_PORT=${{ secrets.OED_SERVER_PORT }}
                  OED_DB_USER=${{ secrets.OED_DB_USER }}
                  OED_DB_DATABASE=${{ secrets.OED_DB_DATABASE }}
                  OED_DB_TEST_DATABASE=${{ secrets.OED_DB_TEST_DATABASE }}
                  OED_DB_PASSWORD=${{ secrets.OED_DB_PASSWORD }}
                  OED_DB_PORT=${{ secrets.OED_DB_PORT }}
                  OED_TOKEN_SECRET=${{ secrets.OED_TOKEN_SECRET }}
                  EOF

            - name: Build & start containers
              run: |
                  docker compose -f docker-compose.ci.yml build
                  docker compose -f docker-compose.ci.yml up -d

            - name: Wait for database to be healthy
              run: docker compose -f docker-compose.ci.yml ps

            - name: Install deps & run checks
              run: |
                  docker compose -f docker-compose.ci.yml run --rm web \
                    sh -c "\
                      git config --global --add safe.directory /usr/src/app && \
                      npm ci && \
                      npm run check:header && \
                      npm run check:typescript && \
                      npm run check:types && \
                      npm run check:lint \
                    "

            - name: Run unit & integration tests
              run: |
                  docker compose -f docker-compose.ci.yml run --rm web \
                    sh -c "npm ci && npm test"

            - name: Tear down
              if: always()
              run: docker compose -f docker-compose.ci.yml down -v
